# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  # How it's going to find the pods it creates
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      # Label that is going to be applied to the pod
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: anushkaxag/auth
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: JWT_KEY
              # Value from secret created
              valueFrom:
                secretKeyRef:
                  # Name of the secret
                  name: jwt-secret
                  # all keys of key-value pair inside secret
                  key: JWT_KEY

---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  # deafault Servie - Cluster IP Service
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
