apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          # In the Docker Hub, there is a mongo image
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  # deafault Servie - Cluster IP Service
  # Selector - telling service which pods it is going to govern access to
  # Find any pod with an label of tickets-mongo
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      # By defualt, mongodb listens to incoming traffic on port 27017
      port: 27017
      targetPort: 27017
